# Generated by Django 5.0.6 on 2024-06-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ayuda',
            fields=[
                ('id_ayuda', models.AutoField(db_column='idAyuda', primary_key=True, serialize=False)),
                ('ayuda', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=20)),
                ('cantidad_necesaria_prod', models.CharField(max_length=2)),
                ('valor_producto', models.CharField(max_length=5)),
                ('id_ayuda', models.ForeignKey(db_column='id_ayuda', on_delete=django.db.models.deletion.CASCADE, to='animales.ayuda')),
            ],
        ),
    ]
